# Generated by Django 6.0.2 on 2026-04-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_financialdata_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdata',
            name='origin',
            field=models.CharField(choices=[('Yahoo Finance', 'Yf'), ('Provider', 'Provider'), ('Financial Times', 'Ft')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='financialdata',
            index=models.Index(fields=['id_object', 'date', 'field'], name='findata_obj_date_field_idx'),
        ),
    ]
